name: Deploy hackathon 2023

on:
  repository_dispatch:
    types: [deploy_hackathon_2023]
  workflow_dispatch:

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        shell: bash
        run: |
         eval `ssh-agent -s`
         mkdir -p /home/runner/.ssh/
         touch /home/runner/.ssh/id_rsa
         echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa
         chmod 700 /home/runner/.ssh/id_rsa
      - name: Run ansible script
        shell: bash
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          #CI_REGISTRY: ${{ secrets.DISPATCH_TOKEN }}
          CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
          CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
          SSH_KEY: /home/runner/.ssh/id_rsa

          playbook: deploy_hackathon_2023.yaml
          image_tag: ${{ github.event.client_payload.image_tag }}
          ansible_tags: ${{ github.event.client_payload.ansible_tags }}
        run: |
          service ssh status
          ansible-playbook -i ci-env.yaml -i inventory playbooks/$playbook -e image_tag=$image_tag --tags "$ansible_tags"
